import React, {Suspense} from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import Header from "@/app/_components/Header/Header";
import Footer from "@/app/_components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        `}
      >
       <Suspense fallback={<LoadingSpinner />}>
          <main>
              {/*<Header />*/}
              <Providers>
                  {children}
              </Providers>
              {/*<Footer />*/}
          </main>
       </Suspense>
      </body>
    </html>
  );
}

function LoadingSpinner() {
    return (
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
            <p>Loading...</p>
        </div>
    );
}
